// <auto-generated />
using System;
using Medical_Shop_MVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Medical_Shop_MVC.Migrations
{
    [DbContext(typeof(MEDContext))]
    partial class MEDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Medical_Shop_MVC.Models.Doctors", b =>
                {
                    b.Property<int>("DoctorID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DoctorDescription");

                    b.Property<int?>("DoctorEnterpriseMedID");

                    b.Property<string>("DoctorName");

                    b.Property<string>("DoctorPhone");

                    b.Property<string>("DoctorSurname");

                    b.Property<string>("Price");

                    b.Property<int?>("doctorTypeSpecID");

                    b.HasKey("DoctorID");

                    b.HasIndex("DoctorEnterpriseMedID");

                    b.HasIndex("doctorTypeSpecID");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Medical_Shop_MVC.Models.Medical_Enterprise", b =>
                {
                    b.Property<int>("MedID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MedAddress");

                    b.Property<string>("MedDescription");

                    b.Property<string>("MedName");

                    b.Property<string>("Time_at");

                    b.HasKey("MedID");

                    b.ToTable("Medical_Enterprise");
                });

            modelBuilder.Entity("Medical_Shop_MVC.Models.Medicine", b =>
                {
                    b.Property<int>("MedicineID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contradication");

                    b.Property<string>("Description");

                    b.Property<string>("Img");

                    b.Property<string>("MedicineCode");

                    b.Property<string>("Name");

                    b.Property<string>("Price");

                    b.Property<int>("Quantity");

                    b.Property<string>("Use_in_case");

                    b.HasKey("MedicineID");

                    b.ToTable("Medicine");
                });

            modelBuilder.Entity("Medical_Shop_MVC.Models.Pharmacy", b =>
                {
                    b.Property<int>("PharmID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PharmAddress");

                    b.Property<string>("PharmName");

                    b.Property<string>("PharmPhone");

                    b.Property<string>("Time_at");

                    b.HasKey("PharmID");

                    b.ToTable("Pharmacy");
                });

            modelBuilder.Entity("Medical_Shop_MVC.Models.Specialization", b =>
                {
                    b.Property<int>("SpecID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SpecDescription");

                    b.Property<string>("SpecName");

                    b.HasKey("SpecID");

                    b.ToTable("Specialization");
                });

            modelBuilder.Entity("Medical_Shop_MVC.Models.Doctors", b =>
                {
                    b.HasOne("Medical_Shop_MVC.Models.Medical_Enterprise", "DoctorEnterprise")
                        .WithMany()
                        .HasForeignKey("DoctorEnterpriseMedID");

                    b.HasOne("Medical_Shop_MVC.Models.Specialization", "doctorType")
                        .WithMany()
                        .HasForeignKey("doctorTypeSpecID");
                });
#pragma warning restore 612, 618
        }
    }
}
